# Generated by Django 6.0.6 on 2026-06-13 13:57
from django.contrib.auth.management import create_permissions
from django.db import migrations

SEED_CHARITIES = [
    ("Black Leaders Detroit", "https://www.blackleadersdetroit.org/"),
    ("Out Front Kalamazoo", "https://www.outfrontkzoo.org/donate/"),
    ("ACLU of Michigan", "https://www.aclumich.org/ways-give/"),
    ("Black United Fund of Michigan", "https://www.bufmi.org/donate/"),
    ("Affirmations", "https://goaffirmations.org/donate/"),
    ("Ferncare Free Clinic", "https://ferncare.org/donate/"),
    ("LGBT Detroit", "https://www.lgbtdetroit.org/donate/"),
    ("Ruth Ellis Center", "https://www.ruthelliscenter.org/"),
    ("The Corner Health Center", "https://cornerhealth.org/"),
    ("Jim Toy Community Center", "https://www.jimtoycenter.org/donate/"),
    ("Ozone House", "https://ozonehouse.org/donate-now/"),
    ("Keep Growing Detroit", "https://www.detroitagriculture.net/donatehere/"),
    ("Athlete Ally", "https://www.athleteally.org/"),
    ("Glisten", "https://glisten.org/campaigns/changing-the-game/"),
    ("NAACP", "https://naacp.org/donate/"),
    (
        "National Center for LGBTQ Rights",
        "https://www.nclrights.org/get-involved/donate-now/",
    ),
    ("National Urban League", "https://nul.org/donate/"),
    ("The Trevor Project", "https://give.thetrevorproject.org/campaign/797408/donate/"),
    ("You Can Play", "https://www.youcanplay.org/give/"),
    ("Black LGBTQ+ Liberation, Inc.", "https://www.blinc.love/donate/"),
    ("BlaqOut", "https://blaqout.org/donate/"),
    ("Ella Baker Center", "https://ellabakercenter.org/donate/"),
]

SEED_GROUPS = {
    # Approve/reject donations and view/delete their receipts.
    "approval_admin": {
        "donation": ["add", "change", "delete", "view"],
    },
    # Full admin actions on charities
    "charity_admin": {
        "charity": ["add", "change", "delete", "view"],
    },
    # Everything in the api app (charities, receipts, donations, stats),
    # but nothing in auth (users/groups).
    "full_admin": {
        "charity": ["add", "change", "delete", "view"],
        "donation": ["add", "change", "delete", "view"],
        "donationreceipt": ["add", "change", "delete", "view"],
        "sitestats": ["change", "view"],
    },
    # View and change site stats
    "stats_admin": {
        "sitestats": ["view", "change"],
    },
}


def seed_charities(apps, schema_editor):
    Charity = apps.get_model("api", "Charity")
    for name, url in SEED_CHARITIES:
        Charity.objects.update_or_create(
            name=name,
            defaults={"url": url, "approved": True},
        )


def unseed_charities(apps, schema_editor):
    Charity = apps.get_model("api", "Charity")
    names = [name for name, _ in SEED_CHARITIES]
    Charity.objects.filter(name__in=names).delete()


def ensure_api_permissions():
    from django.apps import apps as global_apps

    app_config = global_apps.get_app_config("api")
    app_config.models_module = app_config.models_module or True
    create_permissions(app_config, verbosity=0)


def seed_groups(apps, schema_editor):
    ensure_api_permissions()
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    for group_name, model_perms in SEED_GROUPS.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        codenames = [
            f"{action}_{model}"
            for model, actions in model_perms.items()
            for action in actions
        ]
        perms = Permission.objects.filter(
            content_type__app_label="api", codename__in=codenames
        )
        group.permissions.set(perms)


def unseed_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=SEED_GROUPS.keys()).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        # seed_groups requires the contenttypes and auth
        # schemas to be fully migrated first
        ("auth", "__latest__"),
        ("contenttypes", "__latest__"),
    ]

    operations = [
        migrations.RunPython(seed_charities, unseed_charities),
        migrations.RunPython(seed_groups, unseed_groups),
    ]
