# Generated by Django 6.0.7 on 2026-07-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_seed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="approval_notes",
            field=models.TextField(
                blank=True,
                help_text="Optional internal notes about this donation's approval",
            ),
        ),
    ]
