# Generated by Django 6.0.7 on 2026-07-16 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_donation_approval_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="Client IP that reported this donation", null=True
            ),
        ),
        migrations.AddField(
            model_name="donationreceipt",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="Client IP that uploaded this receipt", null=True
            ),
        ),
        migrations.CreateModel(
            name="Ban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("admin", "Admin"), ("auto", "Auto")], max_length=5
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(unique=True)),
                ("reason", models.CharField(max_length=255)),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banned_ips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
